version: '3.5'
services:
  spring-boot-db:
    container_name: spring-boot-db
    build:
      context: ./docker/database
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: curso_java_react
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - spring-boot-db-data:/var/lib/mysql

volumes:
  spring-boot-db-data: